@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjc2LCJ1c2VyTmFtZSI6InF1aXp3aXoiLCJpYXQiOjE3MDI1OTI3NDB9.MoAYTE3yVkT2xln5tLvG_6pVU__yFyaPsRtOrFqWnDk

### Read all categories
GET {{baseUrl}}/quizzes/categories

### Read all quizzes by category
GET {{baseUrl}}/quizzes/readAllQuizzesByCategories/?label=Mathématiques

### Delete the quiz with ID == 3
DELETE {{baseUrl}}/quizzes/3

#### Create a quiz with one question using the user token
POST {{baseUrl}}/quizzes
Content-Type: application/json
authorization: {{token}}

{
    "title": "Calcule",
    "category": "Mathématiques",
    "questions": [
        [
            "2*2",
            "4",
            "10",
            "2.5",
            "3"
        ]
    ]
}



######### ERROR OPERATION  ###########

### Read quiz which does not exists
GET {{baseUrl}}/quizzes/200
