@baseUrl = http://localhost:3000

### Liste de tous les utilisateurs
GET {{baseUrl}}/users

### Modification d'un champ d'un utilisateur, ici l'username
PATCH {{baseUrl}}/users/123
Content-Type: application/json

{
    "username": "nouveau pseudo"
}

### Enregistrer un nouvel utilisateur
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "username":"jean",
    "password":"jean"
}


### Connexion avec un utilisateur existant
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username":"jean",
    "password":"jean"
}

######### ERROR OPERATION  ###########

### Enregistrement d'un utilisateur avec un nom d'utilisateur et un mot de passe vides
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "username":"",
    "password":""
}

### Enregistrement d'un utilisateur avec un nom d'utilisateur mais sans mot de passe
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "username":"jean",
    "password":""
}

### Connexion d'un utilisateur avec un mot de passe mais sans nom d'utilisateur
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username":"",
    "password":"jean"
}

### Enregistrement d'un utilisateur avec un mot de passe mais sans nom d'utilisateur
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "username":"",
    "password":"jean"
}

### Connexion d'un utilisateur avec un nom d'utilisateur mais sans mot de passe
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username":"hello",
    "password":"hello"
}